### ISSUE TITLE
Biometrics on Boot and Disable Secure Flag don't work

### ISSUE THREAD

**Issue by CompuGeniusCode** [Firefds/FirefdsKit#41] opened 2024-01-14 05:17 UTC
**Describe the bug**
Biometrics on Boot, Disable Secure Flag ~~, Editing stuff in Status Bar, Spoofing System Status~~

**Device:**
 - Device: S23 Plus
 - Chipset: Snapdragon
 - Model: SM-S916B

**Xposed or Logcat logs**
https://github.com/Firefds/FirefdsKit/files/13930385/LSPosed_2024-01-14T00_00_56.253515.zip

**Additional context**
#38

**Comment by Firefds** [comment] 2024-01-14 12:38
* Biometrics on Boot - Will try to fix
* Editing stuff in Status Bar - what is this? If you mean adding network speed menu, the location has changed to `Settings --> Notifications --> Advanced settings --> Show network speed in real time`.
* Spoofing System Status - I don't see any errors regarding this. Please go to Status information and `Phone status` should be `Official`. If not send screenshot + logs (new logs after you navigated there)

**Comment by CompuGeniusCode** [comment] 2024-01-14 12:45
> * Biometrics on Boot - Will try to fix

Thank you.

>     * Editing stuff in Status Bar - what is this? If you mean adding network speed menu, the location has changed to `Settings --> Notifications --> Advanced settings --> Show network speed in real time`.

Ohhhh. I didn't realize it appears as a system setting haha. Got it.

>     * Spoofing System Status - I don't see any errors regarding this. Please go to Status information and `Phone status` should be `Official`. If not send screenshot + logs (new logs after you navigated there)

This DOES show official, but I thought this would remove the Knox warning on boot and allow system updates, no? What's the practical point of this setting?

**Comment by Firefds** [comment] 2024-01-14 12:48
> This DOES show official, but I thought this would remove the Knox warning on boot and allow system updates, no? What's the practical point of this setting?

No, this does not remove the Knox warning. Xposed doesn't have that ability as that warning is even before boot. You will need to search for a guide on how to remove it for your device.
System updates will not work anyway, as you are using Magisk.
The point is to show `Official` and not `Custom`.

**Comment by CompuGeniusCode** [comment] 2024-01-14 12:51
Alright, well in that case, I guess it works. Should I leave this issue open until you fix Biometrics on Boot, or close it?

**Comment by CompuGeniusCode** [comment] 2024-01-22 22:08
Disabling Secure Flag doesn't work either.

**Comment by Firefds** [comment] 2024-01-29 12:13
Can't fix biomertrics on reboot - removed.
Can't reproduce secure flag not working.
Closing.
If it still doesn't work for you, open an issue and attach logs after trying to take a screenshot.

**Closed as completed by Firefds** 2024-01-29 12:13 UTC
Labels: bug
